ProjectLily/src/art/routes.py
from flask import Blueprint, render_template, request
from src.models import ArtImages, Products


art = Blueprint('art', __name__)

@art.route("/cart")
def cart():
    """
        Cart route
    """
    return render_template('cart.html', title="Cart")

@art.route("/gallery")
def gallery():
    """
        Gallery route
    """
    page = request.args.get('page', 1, type=int)
    images = ArtImages.query.paginate(page=page, per_page=6)
    return render_template('gallery.html', title="Gallery", images=images)

@art.route("/image<int:image_id>")
def view_image(image_id):
    """
        View selected image route
    """
    image = ArtImages.query.get_or_404(image_id)
    return render_template('viewimage.html', image=image)

@art.route("/shop")
def shop():
    """
        Shop route
    """
    page = request.args.get('page', 1, type=int)
    products = Products.query.paginate(page=page, per_page=6)
    return render_template('shop.html', title="Shop", products=products)

@art.route("/product<int:product_id>")
def view_product(product_id):
    """
        View selected product
    """
    product = Products.query.get_or_404(product_id)
    return render_template('viewproduct.html', product=product)

ProjectLily/src/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="left-aligned about-size">
            <img class="rounded-circle account-img" src="static/images/profile.jpg">
            <div id="personal-info">
                <h3 class="account-heading">Lily Foster</h3>
                <p class="text-secondary">16 Years Old - Irish</p>
            </div>
            <div id="hobbies">
                <h3 class="account-heading">Hobbies & Interests:</h3>
                <p class="text-secondary">
                    Drawing, Performing, Movies
                    Irish Dancing, Harry Potter, Marvel
                </p>
            </div>
            <div id="contact-info">
                <h3 class="account-heading">Contact:</h3>
                <div class="text-secondary">
                    <p>Email: lilyfosterart.business@gmail.com</p> <p>Phone: /enter/</p>
                </div>
            </div>
        </div>
    </div>    
{% endblock content %}

ProjectLily/src/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="left-aligned">
            <div id="account-info">
                <h2 class="account-heading">Account Information:</h2>
                <p class="text-secondary">Name: {{ current_user.name }}</p>
                <p class="text-secondary">Email: {{ current_user.email }}</p>
                <p class="text-secondary">Phone: {{ current_user.phone }}</p>
            </div>
            <div id="update-info">
                <h2 class="account-heading">Update Account Info:</h2>
                <!--Forms here-->
                <form method="POST", action="", class="login" id="update">
                    {{ form.hidden_tag() }}
                    <div>
                        {% if form.name.errors %}
                            {{ form.name(class="userinput-invalid", placeholder=form.name.label.text) }}
                            <div class="invalid-tips">
                                {% for error in form.name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.name(class="userinput", placeholder=form.name.label.text) }}
                        {% endif %}
                    </div>
                    <div>
                        {% if form.email.errors %}
                            {{ form.email(class="userinput-invalid", placeholder=form.email.label.text) }}
                            <div class="invalid-tips">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="userinput", placeholder=form.email.label.text) }}
                        {% endif %}
                    </div>
                    <div>
                        {% if form.phone.errors %}
                            {{ form.phone(class="userinput-invalid", placeholder=form.phone.label.text) }}
                            <div class="invalid-tips">
                                {% for error in form.phone.errors %}
                                    <span>Phone number needs to be a number.</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.phone(class="userinput", placeholder=form.phone.label.text) }}
                        {% endif %}
                    </div>
                    <small class="hover-underline-animation">
                    <a href="{{ url_for('users.request_password_reset') }}">Update Password</a>
                    </small>
                    <div>
                        {{ form.submit(class="btn btn-outline-dark btn-lg") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

ProjectLily/src/templates/cart.html
{% extends "layout.html" %}
{% block content %}
    <div class="text">
        Cart...
    </div>
{% endblock content %}

ProjectLily/src/templates/contact.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h2 class="account-heading">Send Me an Email:</h2>
        <!--Forms here-->
        <form method="POST", action="", class="login" id="contact">

            {{ form.hidden_tag() }}

            {% if not current_user.is_authenticated %}
            <div>
                {% if form.name.errors %}
                    {{ form.name(class="userinput-invalid", placeholder=form.name.label.text) }}
                    <div class="invalid-tips">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="userinput", placeholder=form.name.label.text) }}
                {% endif %}
            </div>

            <div>
                {% if form.email.errors %}
                    {{ form.email(class="userinput-invalid", placeholder=form.email.label.text) }}
                    <div class="invalid-tips">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="userinput", placeholder=form.email.label.text) }}
                {% endif %}
            </div>

            <div>
                {% if form.phone.errors %}
                    {{ form.phone(class="userinput-invalid", placeholder=form.phone.label.text) }}
                    <div class="invalid-tips">
                        {% for error in form.phone.errors %}
                            <span>Phone number needs to be a number.</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.phone(class="userinput", placeholder=form.phone.label.text) }}
                {% endif %}
            </div>
            {% endif %}

            <div>
                {% if form.subject.errors %}
                    {{ form.subject(class="userinput-invalid", placeholder=form.subject.label.text) }}
                    <div class="invalid-tips">
                        {% for error in form.subject.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.subject(class="userinput", placeholder=form.subject.label.text) }}
                {% endif %}
            </div>

            <div>
                {% if form.email_content.errors %}
                    {{ form.email_content(class="userinput-invalid", placeholder=form.email_content.label.text) }}
                    <div class="invalid-tips">
                        {% for error in form.email_content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email_content(class="userinput", placeholder=form.email_content.label.text) }}
                {% endif %}
            </div>

            <div>
                {{ form.submit(class="btn btn-outline-dark btn-lg") }}
            </div>

        </form>
    </div>
{% endblock content %}

ProjectLily/src/templates/gallery.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h1 style="font-weight: bolder;">There are {{ images.total }} art pieces in this gallery</h1>
        <div class="images">
            {% for image in images.items %}
                <a href="{{ url_for('art.view_image', image_id=image.id) }}"><img class="galleryIMG" src="static/images/{{ image.filename }}"/></a>
            {% endfor %}
        </div>
    </div>
    <div class="page-buttons">
        {% for page_num in images.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
            {% if page_num %}
                {% if images.page == page_num %}
                    <a class="btn btn-dark" href="{{ url_for('art.gallery', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-dark" href="{{ url_for('art.gallery', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>
{% endblock content %}

ProjectLily/src/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <div class="text">
        <P>
            Hey there, this is a website to showcase the art and work of Lily Foster. 
            Her work is all done on paper and covers a variety of styles, including;
            Shaded drawings, Coloured drawings using both pencils and markers. The subjects
            vary from movie characters, to pets and family.
        </P>

        <P>
            What can you find and do on this website? The left contains the sidebar which allows you to
            navigate through the website. (On mobile you can click/touch, the three bar icon in the top 
            left to access the sidebar menu). You can visit the Gallery, where you can view the back catalogue
            of all of Lily's artwork. You can sign up for an account which allows you to get in touch with
            Lily. You can get in touch for whatever reason, your comments, suggestions and requests are always
            very welcome.
        </P>

        <!--Add paragraph about shop and cart when implemented.-->
    </div>
{% endblock content %}

ProjectLily/src/templates/request_password_reset.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
          <div class="media-body">
            <h2 class="account-heading">Account Email:</h2>
          </div>
        </div>
        <!--Forms here-->
        <form method="POST", action="", class="login" id="reset_request">

          {{ form.hidden_tag() }}

          <div>
              {% if form.email.errors %}
                  {{ form.email(class="userinput-invalid", placeholder=form.email.label.text) }}
                  <div class="invalid-tips">
                      {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.email(class="userinput", placeholder=form.email.label.text) }}
              {% endif %}
          </div>

          <div>
              {{ form.submit(class="btn btn-outline-dark btn-lg", style="font-size: clamp(0.75rem, 1vw + 0.25rem, 1rem);") }}
          </div>

      </form>
    </div>
{% endblock content %}

ProjectLily/src/templates/reset_password.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
          <div class="media-body">
            <h2 class="account-heading">Enter your new password:</h2>
          </div>
        </div>
        <!--Forms here-->
        <form method="POST", action="", class="login" id="new_password">

          {{ form.hidden_tag() }}

          <div>
              {% if form.password.errors %}
                  {{ form.password(class="userinput-invalid", placeholder=form.password.label.text, id="resetPassword") }}
                  <div class="invalid-tips">
                      {% for error in form.password.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.password(class="userinput", placeholder=form.password.label.text, id="resetPassword") }}
              {% endif %}
          </div>

          <div>
              {% if form.confirm_password.errors %}
                  {{ form.confirm_password(class="userinput-invalid", placeholder=form.confirm_password.label.text, id="resetPassword2") }}
                  <div class="invalid-tips">
                      {% for error in form.confirm_password.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.confirm_password(class="userinput", placeholder=form.confirm_password.label.text, id="resetPassword2") }}
              {% endif %}
          </div>

          <div>
            <small>Show Password</small> <input type="checkbox" onclick="switchPassword('resetPassword'), switchPassword('resetPassword2')">
        </div>

          <div>
              {{ form.submit(class="btn btn-outline-dark btn-lg") }}
          </div>

      </form>
    </div>
{% endblock content %}

ProjectLily/src/templates/shop.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h1 style="font-weight: bolder;">There are {{ products.total }} prints available for purchase</h1>
        <div class="products">
            {% for product in products.items %}
                <div class="product-card">
                    <a href="{{ url_for('art.view_product', product_id=product.id) }}" class="product-link">
                        <img src="static/products/{{ product.filename }}" alt="" class="product-img"></a>
                    <div class="product">
                        <div class="product-info">
                            {% if product.sale %}
                                <div class="sale">
                                    <p class="sale-text">
                                        SALE - {{ product.sale_percent }}% OFF!
                                    </p>
                                </div>
                            {% endif %}
                            <p class="product-title">
                                {{ product.title }}
                            </p>
                            <div class="pricing">
                                <p class="price">€{{ product.price }}</p>
                                {% if product.sale %}
                                    <p class="previous-price"><s>€{{ product.previous_price }}</s></p>
                                {% endif %}
                            </div>
                        </div>
                        <button class="product-add">
                            Add to Cart
                        </button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="page-buttons">
        {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
            {% if page_num %}
                {% if products.page == page_num %}
                    <a class="btn btn-dark" href="{{ url_for('art.shop', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-dark" href="{{ url_for('art.shop', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>
{% endblock content %}

ProjectLily/src/templates/signin.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" class="login" id="signin">
            {{ in_form.hidden_tag() }}
            <div>
                {% if in_form.email.errors %}
                    {{ in_form.email(class="userinput-invalid", placeholder=in_form.email.label.text) }}
                    <div class="invalid-tips">
                        {% for error in in_form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ in_form.email(class="userinput", placeholder=in_form.email.label.text) }}
                {% endif %}
            </div>
            <div>
                {% if in_form.password.errors %}
                    {{ in_form.password(class="userinput-invalid", placeholder=in_form.password.label.text, id="signInPassword") }}
                    <div class="invalid-tips">
                        {% for error in in_form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ in_form.password(class="userinput", placeholder=in_form.password.label.text, id="signInPassword") }}
                {% endif %}
            </div>
            <div>
                <small>Show Password</small>
                <input type="checkbox" onclick="switchPassword('signInPassword')">
            </div>
            <div>
                <small>Stay logged in?</small>
                {{ in_form.remember(class="form-check-inline") }}
            </div>
            <small class="hover-underline-animation">
                <a href="{{ url_for('users.request_password_reset') }}">Forgot Password?</a>
            </small>
            <div>
                {{ in_form.submit(class="btn btn-outline-dark btn-lg") }}
            </div>
            <div style="border-top: 1px solid #000000;">
                <small class="text-muted" style="font-weight: bolder; font-size: clamp(0.5rem, 1vw + 0.25rem, 1rem);">
                    Need An Account? - <a class="hover-underline-animation ml-2" href="{{ url_for('users.signup') }}">Sign Up Now</a>
                </small>
            </div>
        </form>
    </div>
{% endblock content %}

ProjectLily/src/templates/signup.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST", action="", class="login" id="signup">

            {{ up_form.hidden_tag() }}

            <div>
                {% if up_form.firstname.errors %}
                    {{ up_form.firstname(class="userinput-invalid", placeholder=up_form.firstname.label.text) }}
                    <div class="invalid-tips">
                        {% for error in up_form.firstname.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ up_form.firstname(class="userinput", placeholder=up_form.firstname.label.text) }}
                {% endif %}
            </div>

            <div>
                {% if up_form.lastname.errors %}
                    {{ up_form.lastname(class="userinput-invalid", placeholder=up_form.lastname.label.text) }}
                    <div class="invalid-tips">
                        {% for error in up_form.lastname.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ up_form.lastname(class="userinput", placeholder=up_form.lastname.label.text) }}
                {% endif %}
            </div>

            <div>
                {% if up_form.email.errors %}
                    {{ up_form.email(class="userinput-invalid", placeholder=up_form.email.label.text) }}
                    <div class="invalid-tips">
                        {% for error in up_form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ up_form.email(class="userinput", placeholder=up_form.email.label.text) }}
                {% endif %}
            </div>

            <div>
                {% if up_form.phone.errors %}
                    {{ up_form.phone(class="userinput-invalid", placeholder=up_form.phone.label.text) }}
                    <div class="invalid-tips">
                        {% for error in up_form.phone.errors %}
                            <span>Phone number needs to be a number.</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ up_form.phone(class="userinput", placeholder=up_form.phone.label.text) }}
                {% endif %}
            </div>

            <div>
                {% if up_form.password.errors %}
                    {{ up_form.password(class="userinput-invalid", placeholder=up_form.password.label.text, id="signUpPassword") }}
                    <div class="invalid-tips">
                        {% for error in up_form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ up_form.password(class="userinput", placeholder=up_form.password.label.text, id="signUpPassword") }}
                {% endif %}
            </div>

            <div>
                {% if up_form.confirm_password.errors %}
                    {{ up_form.confirm_password(class="userinput-invalid", placeholder=up_form.confirm_password.label.text, id="signUpPassword2") }}
                    <div class="invalid-tips">
                        {% for error in up_form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ up_form.confirm_password(class="userinput", placeholder=up_form.confirm_password.label.text, id="signUpPassword2") }}
                {% endif %}
            </div>

            <div>
                <small>Show Password</small> <input type="checkbox" onclick="switchPassword('signUpPassword'), switchPassword('signUpPassword2')">
            </div>

            <div>
                {{ up_form.submit(class="btn btn-outline-dark btn-lg") }}
            </div>
            <div style="border-top: 1px solid #000000;">
                <small class="text-muted" style="font-weight: bolder; font-size: clamp(0.5rem, 1vw + 0.25rem, 1rem);">
                    Already have an Account? - <a class="hover-underline-animation ml-2" href="{{ url_for('users.signin') }}">Sign In Now</a>
                </small>
            </div>
        </form>
    </div>
{% endblock content %}

ProjectLily/src/templates/updateDB.html
{% extends "layout.html" %}
{% block content %}
<div class="test">
    <p class="hey">
        HEY!!!
    </p>
</div>
{% endblock content %}

ProjectLily/src/templates/viewproduct.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="left-aligned product-item">
            <div class="product-card view-product">
                <img src="static/products/{{ product.filename }}" alt="" class="product-img">
                <div class="product">
                    <div class="product-info">
                        {% if product.sale %}
                            <div class="sale">
                                <p class="sale-text">
                                    SALE - {{ product.sale_percent }}% OFF!
                                </p>
                            </div>
                        {% endif %}
                        <p class="product-title">
                            {{ product.title }}
                        </p>
                        <div class="pricing">
                            <p class="price">€{{ product.price }}</p>
                            {% if product.sale %}
                                <p class="previous-price"><s>€{{ product.previous_price }}</s></p>
                            {% endif %}
                        </div>
                    </div>
                    <button class="product-add">
                        Add to Cart
                    </button>
                </div>
            </div>
            <div class="product-description">
                <h2 class="account-heading">Product Description:</h2>
                <h2 class="image-desc">{{ product.description }}</h2>
            </div>
        </div>
    </div>
{% endblock content %}